# Generated by Django 5.0.6 on 2024-07-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customusersocialauth',
            table='custom_user_social_auth',
        ),
    ]
