# Generated by Django 5.0.6 on 2024-07-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customusersocialauth_table'),
        ('organizer', '0014_alter_events_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customusersocialauth',
            unique_together={('provider', 'uid')},
        ),
        migrations.AlterField(
            model_name='customusersocialauth',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customusersocialauth',
            name='provider',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customusersocialauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_auth', to='organizer.eventnestusers'),
        ),
        migrations.AlterModelTable(
            name='customusersocialauth',
            table=None,
        ),
        migrations.RemoveField(
            model_name='customusersocialauth',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customusersocialauth',
            name='updated_at',
        ),
    ]
