# Generated by Django 5.0.6 on 2024-07-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customusersocialauth_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserSocialAuth',
        ),
    ]
