apiVersion: v1
kind: Service
metadata:
  name: django-postgres
  labels:
    app: django
spec:
  ports:
    - port: 5432
  selector:
    app: django
    tier: postgres

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-postgres-pvc
  labels:
    app: django
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: django-postgres
spec:
  selector:
    matchLabels:
      app: django
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: django-postgres-pvc
      containers:
      - image: zimmadwaraich/event_nest:postgres
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
