# Generated by Django 5.0.6 on 2024-08-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnestusers',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='eventnestusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
