# Generated by Django 5.0.6 on 2024-08-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventnestusers',
            old_name='name',
            new_name='username',
        ),
    ]
