# Generated by Django 5.0.6 on 2024-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_remove_eventnestusers_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='registration_count',
            field=models.IntegerField(null=True),
        ),
    ]
