# Generated by Django 5.0.6 on 2024-07-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_events_registration_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='video',
            field=models.FileField(default=0, upload_to='videos/'),
        ),
    ]
