# Generated by Django 5.0.6 on 2024-07-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_alter_events_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='registration_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
