# Generated by Django 5.0.6 on 2024-07-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_alter_events_registration_count_alter_events_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='present_attendee',
            field=models.IntegerField(default=0),
        ),
    ]
