# Generated by Django 5.0.6 on 2024-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_events_present_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='present_attendee',
        ),
        migrations.AddField(
            model_name='events',
            name='present_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='registration_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
