# Generated by Django 5.0.6 on 2024-07-03 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_remove_events_present_attendee_events_present_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
