# Generated by Django 5.0.6 on 2024-07-03 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_alter_events_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
