# Generated by Django 5.0.6 on 2024-06-24 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0003_alter_eventnestusers_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.eventnestusers')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.events')),
            ],
        ),
    ]
