# Generated by Django 5.0.6 on 2024-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0004_alter_emailtemplate_subject'),
        ('organizer', '0014_alter_events_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendeeevent',
            index=models.Index(fields=['Attendee', 'event'], name='attendee_at_Attende_cc8c63_idx'),
        ),
    ]
