# Generated by Django 5.0.6 on 2024-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='organization',
            field=models.CharField(default='Code genesis', max_length=40),
            preserve_default=False,
        ),
    ]
