# Generated by Django 5.0.6 on 2024-06-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
