# Generated by Django 5.0.6 on 2024-05-30 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_', '0002_organizer_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='authenticate_.organizer'),
            preserve_default=False,
        ),
    ]
