# Generated by Django 5.0.6 on 2024-05-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_', '0003_events_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_set', to='authenticate_.organizer'),
        ),
    ]
